name: autofix.ci
on:
  pull_request:
  push:
    branches: ['main']
permissions:
  contents: read

jobs:
  frontend_lint_fix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.TOKEN }}
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: pnpm
          cache-dependency-path: frontend/pnpm-lock.yaml

      - run: cd frontend && pnpm install --frozen-lockfile
      - run: cd frontend && pnpx prettier --write . --config .prettierrc
      - run: cd frontend && pnpx eslint . --fix

      - uses: autofix-ci/action@dd55f44df8f7cdb7a6bf74c78677eb8acd40cd0a
  backend_format_fix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.TOKEN }}
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22.5'
          cache-dependency-path: 'backend/go.sum'

      - run: cd backend && go install mvdan.cc/gofumpt@latest
      - run: cd backend && gofumpt -l -w . && git diff --exit-code

      - uses: autofix-ci/action@dd55f44df8f7cdb7a6bf74c78677eb8acd40cd0a
