name: autofix.ci
on:
  pull_request:
  push:
    branches: ['main']
permissions:
  contents: read

jobs:
  autofix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: pnpm
          cache-dependency-path: frontend/pnpm-lock.yaml

      - run: cd frontend && pnpm install --frozen-lockfile
      - run: cd frontend && pnpx prettier --write . --config .prettierrc
      - run: cd frontend && pnpx eslint@8.57.0 . --fix --ext .js,.jsx,.ts,.tsx

      - uses: autofix-ci/action@dd55f44df8f7cdb7a6bf74c78677eb8acd40cd0a
  autofix_go:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22.5'
          cache-dependency-path: 'backend/go.sum'

      # goimports works like gofmt, but also fixes imports.
      # see https://pkg.go.dev/golang.org/x/tools/cmd/goimports
      - run: cd backend && go install golang.org/x/tools/cmd/goimports@latest
      - run: cd backend && goimports -w .

      - uses: autofix-ci/action@dd55f44df8f7cdb7a6bf74c78677eb8acd40cd0a
